name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2.0.1
      - name: install dependencies
        run: bun install
      - name: lint
        run: bun bin/itty.js lint