name: verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2.0.1
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun bin/itty.js build || echo "No build needed - this is the build tool itself"